apiVersion: v1
kind: Pod
metadata:
  name: tomcatapp
  namespace: tomcat
  labels:
    app: tomcatapp
spec:
  containers:
  - name: tomcat
    image: tomcat:latest  # image
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcatappsvc
  namespace: tomcat
spec:
  type: NodePort
  selector:
    app: tomcatapp
  ports:
  - port: 80
    targetPort: 8080
